// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService 暴露聊天。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerPermission 由界面调用：把人在弹窗上的选择回给后端。
 */
export function AnswerPermission(id: string, optionID: string): $CancellablePromise<void> {
    return $Call.ByID(3052488720, id, optionID);
}

/**
 * Cancel 停当前这一轮。
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(2433544267);
}

/**
 * HarnessLogPath 是后端日志的位置（配置页要能告诉人去哪看）。
 */
export function HarnessLogPath(): $CancellablePromise<string> {
    return $Call.ByID(4194566492);
}

/**
 * Resume 恢复历史会话。
 */
export function Resume(sessionID: string): $CancellablePromise<$models.AgentStatus> {
    return $Call.ByID(528559866, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveSettings 存设置。存完立刻重新检查一次（让人当场看到「补齐了没有」）。
 */
export function SaveSettings(v: $models.AppSettingsView): $CancellablePromise<$models.AppSettingsView> {
    return $Call.ByID(1999048037, v).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Send 发一句。
 * 
 * **立刻返回**：一轮可能跑几分钟，界面靠事件拿更新；一轮结束会发 EventAgentTurn。
 */
export function Send(text: string): $CancellablePromise<void> {
    return $Call.ByID(3612199103, text);
}

/**
 * Sessions 列当前 vault 的历史会话（已按 cwd 过滤，不会串到别的项目）。
 */
export function Sessions(): $CancellablePromise<$models.AgentSessionRef[]> {
    return $Call.ByID(1371309756).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetModel 改当前会话的模型（会话级，不是全局配置）。
 */
export function SetModel(value: string): $CancellablePromise<$models.AgentStatus> {
    return $Call.ByID(4242829424, value).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Settings 读设置（含逐条后端检查）。
 */
export function Settings(): $CancellablePromise<$models.AppSettingsView> {
    return $Call.ByID(3908835128).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Start 起后端并开会话。
 */
export function Start(): $CancellablePromise<$models.AgentStatus> {
    return $Call.ByID(3039591599).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Status 返回聊天面板状态。
 */
export function Status(): $CancellablePromise<$models.AgentStatus> {
    return $Call.ByID(3659612799).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Stop 关掉后端。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2999683061);
}

// Private type creation functions
const $$createType0 = $models.AgentStatus.createFrom;
const $$createType1 = $models.AppSettingsView.createFrom;
const $$createType2 = $models.AgentSessionRef.createFrom;
const $$createType3 = $Create.Array($$createType2);
