// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService 暴露断言库与质量。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Assertions 分页返回断言。
 */
export function Assertions(f: $models.FilterInput, limit: number, offset: number): $CancellablePromise<$models.AssertionPage> {
    return $Call.ByID(4257491431, f, limit, offset).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * EntityNames 返回 schema 中声明的实体名。
 */
export function EntityNames(): $CancellablePromise<string[]> {
    return $Call.ByID(2155983627).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Quality 返回每个实体的数据质量。
 * 
 * 以 schema 声明的实体为准：**「声明了却没有数据」正是最该被看见的缺口**，
 * 只遍历库里有数据的实体，它永远不会出现。
 */
export function Quality(): $CancellablePromise<$models.EntityQuality[]> {
    return $Call.ByID(111336079).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Schema 返回全部实体声明。
 */
export function Schema(): $CancellablePromise<$models.EntitySchema[]> {
    return $Call.ByID(2178830797).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SubjectDetail 返回某主体上的全部断言。
 */
export function SubjectDetail(entity: string, subject: string): $CancellablePromise<$models.Item[]> {
    return $Call.ByID(3566904439, entity, subject).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Subjects 返回某实体下的全部主体，供界面做主体选择。
 */
export function Subjects(entity: string): $CancellablePromise<string[]> {
    return $Call.ByID(558894975, entity).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AssertionPage.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.EntityQuality.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.EntitySchema.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Item.createFrom;
const $$createType7 = $Create.Array($$createType6);
