// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocumentService 暴露文档。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * History 返回某个文档的全部修订，登记时间倒序。
 */
export function History(revID: string): $CancellablePromise<$models.DocView[]> {
    return $Call.ByID(4164277593, revID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * List 返回每个文档的当前修订。场景名为空表示全部。
 */
export function List(scenario: string): $CancellablePromise<$models.DocView[]> {
    return $Call.ByID(3186988399, scenario).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Register 登记一份文档（可能是新修订）。
 * 
 * 返回的 `requeued` 是一次同步让多少条断言回到待核验——
 * **不告知人的批量回退就是最坏的那种静默**。
 */
export function Register($in: $models.DocInput): $CancellablePromise<$models.DocRegisterResult> {
    return $Call.ByID(1959574122, $in).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Reject 驳回一份文档。条目保留。
 */
export function Reject(revID: string, by: string, reason: string): $CancellablePromise<$models.DocView> {
    return $Call.ByID(1920136244, revID, by, reason).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Unregistered 返回还没有对应文档的原件。
 * 
 * 「溯源的终点是一个字符串」正是文档层要消灭的状态，
 * 因此剩余多少必须能查出来，而不是靠人感觉。
 */
export function Unregistered(): $CancellablePromise<$models.UnregisteredView[]> {
    return $Call.ByID(833417336).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Usage 返回引用某份文档的断言。
 */
export function Usage(revID: string): $CancellablePromise<$models.Item[]> {
    return $Call.ByID(221820902, revID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Verify 为这份原文背书。核验人必须是人；方法只能是编审。
 */
export function Verify(revID: string, by: string, method: string, reason: string): $CancellablePromise<$models.DocView> {
    return $Call.ByID(2071912138, revID, by, method, reason).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DocView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.DocRegisterResult.createFrom;
const $$createType3 = $models.UnregisteredView.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Item.createFrom;
const $$createType6 = $Create.Array($$createType5);
