// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExperienceService 暴露经验。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppendTurn 追加一段发言。
 * 
 * **没有对应的修改与删除方法**：会话记录是经验的依据，
 * 一旦能改，经验所指向的「第 3 段」就可能已经不是当初那句话了。
 */
export function AppendTurn(sessionID: string, roleKind: string, roleID: string, text: string): $CancellablePromise<$models.SessionView> {
    return $Call.ByID(2834441657, sessionID, roleKind, roleID, text).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Approve 批准一条候选经验。by 必须是人。
 */
export function Approve(id: string, by: string, reason: string): $CancellablePromise<$models.EntryView> {
    return $Call.ByID(1723415335, id, by, reason).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Conflicts 返回冲突分组。**只呈现，不裁决。**
 */
export function Conflicts(scenario: string): $CancellablePromise<$models.ConflictView[]> {
    return $Call.ByID(1629546965, scenario).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * List 返回某场景的经验，按级别与时间排序。场景名为空表示全部。
 */
export function List(scenario: string): $CancellablePromise<$models.EntryView[]> {
    return $Call.ByID(1692919082, scenario).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * OpenSession 新建一段会话记录。
 * 
 * 刻意叫 Open 而不是 Create：会话是**开出来然后往里追加**的，
 * 没有「编辑会话」这个动作。
 */
export function OpenSession(scenario: string, title: string): $CancellablePromise<$models.SessionView> {
    return $Call.ByID(3487814834, scenario, title).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Propose 提出一条候选经验。重复提出同一句话返回已有条目。
 */
export function Propose($in: $models.ProposalInput): $CancellablePromise<$models.EntryView> {
    return $Call.ByID(3385494116, $in).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Refresh 检查全部经验的依赖，标出失效与待重算。
 */
export function Refresh(scenario: string): $CancellablePromise<$models.RefreshResultView> {
    return $Call.ByID(4187308293, scenario).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Reject 驳回一条经验。条目保留——驳回是审计轨迹。
 */
export function Reject(id: string, by: string, reason: string): $CancellablePromise<$models.EntryView> {
    return $Call.ByID(647860061, id, by, reason).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Sessions 返回某场景的会话记录（依据）。
 */
export function Sessions(scenario: string): $CancellablePromise<$models.SessionView[]> {
    return $Call.ByID(2931335891, scenario).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Supersede 用新判断取代旧条目。旧条目保留，状态改为「已被取代」。
 */
export function Supersede(oldID: string, $in: $models.ProposalInput): $CancellablePromise<[$models.EntryView, $models.EntryView]> {
    return $Call.ByID(1592503570, oldID, $in).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

// Private type creation functions
const $$createType0 = $models.SessionView.createFrom;
const $$createType1 = $models.EntryView.createFrom;
const $$createType2 = $models.ConflictView.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = $models.RefreshResultView.createFrom;
const $$createType6 = $Create.Array($$createType0);
