// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FormulaService 暴露公式。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List 返回项目里的全部公式及其验证状态。
 * 
 * **逐个文件加载**而不是一次 LoadDir：一条写坏的公式不该让整页打不开，
 * 它应该被单独指出是哪一条、错在哪。
 */
export function List(): $CancellablePromise<$models.FormulaView[] | null> {
    return $Call.ByID(1903130150);
}
