// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchPreview 是批量操作的预览结果。
 */
export interface BatchPreview {
    "matched": number;
    "where": string;
    "sample": Item[] | null;
}

/**
 * BatchResult 是批量操作的结果。
 */
export interface BatchResult {
    "matched": number;
    "applied": number;
    "failed": number;
    "firstErr": string;
}

/**
 * ConflictGroup 是一组互相冲突的断言。
 */
export interface ConflictGroup {
    "subject": string;
    "predicate": string;
    "claims": Item[] | null;
}

/**
 * DecisionCandidate 是一个候选取值（面向界面）。
 * 
 * 上下文必填：只给一个数字，人无法判断。
 */
export interface DecisionCandidate {
    "index": number;
    "value": string;
    "unit": string;
    "anchor": string;
    "context": string;
    "note": string;
}

/**
 * DecisionItem 是一个待判定事项（面向界面）。
 */
export interface DecisionItem {
    "id": string;
    "entity": string;
    "subject": string;
    "predicate": string;
    "reason": string;
    "context": string;
    "artifact": string;
    "revision": string;
    "source": string;
    "status": string;
    "statusText": string;

    /**
     * Impact 是被引用次数，ImpactReason 是「为什么排在前面」。
     */
    "impact": number;
    "impactReason": string;
    "candidates": DecisionCandidate[] | null;
    "resolution": DecisionResolution | null;
    "deferredBy": string;
    "deferReason": string;

    /**
     * Editable 报告该事项此刻是否还能裁决。它由状态算出，
     * 免得界面自己判断状态——那会让「能不能点」变成第二套规则。
     */
    "editable": boolean;
}

/**
 * DecisionResolution 是一次裁决（面向界面）。
 */
export interface DecisionResolution {
    "choice": number;

    /**
     * ChosenValue 在「都不对」时为空串。
     */
    "chosenValue": string;
    "by": string;
    "reason": string;
    "method": string;
    "evidence": string;
    "at": string;

    /**
     * AssertionID 在「都不对」时为空串。
     */
    "assertionId": string;
}

/**
 * DecisionResult 是一次裁决的结果。
 */
export interface DecisionResult {
    "applied": boolean;
    "status": string;
    "assertionId": string;
    "message": string;
}

/**
 * DecisionStats 是待判定的整体状态。
 */
export interface DecisionStats {
    "open": number;
    "deferred": number;
    "decided": number;
    "missing": number;
    "stale": number;
}

/**
 * FilterInput 是批量筛选条件（面向界面）。
 */
export interface FilterInput {
    "entity": string;
    "status": string;
    "predicate": string;
    "artifact": string;
    "revision": string;
    "confidence": string;
    "subject": string;
    "limit": number;
}

/**
 * HistoryItem 是一条核验记录（面向界面）。
 */
export interface HistoryItem {
    "decision": string;
    "method": string;
    "proposedBy": string;
    "approvedBy": string;
    "reason": string;
    "evidence": string;
    "at": string;
}

/**
 * Item 是队列里的一条断言（面向界面的扁平结构）。
 */
export interface Item {
    "id": string;
    "entity": string;
    "subject": string;
    "predicate": string;
    "value": string;
    "unit": string;
    "confidence": string;
    "status": string;
    "source": string;
    "artifact": string;
    "anchor": string;
    "revision": string;
}

/**
 * QueueItem 是带优先级的队列项。
 * 
 * 除了断言本身，它还带上「为什么排在前面」——排在前面的理由必须可见，
 * 否则人只能盲信排序。
 */
export interface QueueItem {
    "item": Item;
    "tier": string;
    "reason": string;
    "score": number;
    "sampled": boolean;
}

/**
 * Stats 是库的整体状态。
 */
export interface Stats {
    "total": number;
    "byStatus": { [_ in string]?: number } | null;
    "byEntity": { [_ in string]?: number } | null;
    "byConfidence": { [_ in string]?: number } | null;
    "verifications": number;
    "conflicts": number;
}
