// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActorView 是一个参与者（面向界面）。
 */
export interface ActorView {
    "kind": string;
    "id": string;
}

/**
 * AssertionPage 是一页断言。
 */
export interface AssertionPage {
    "items": Item[] | null;
    "total": number;
    "offset": number;
    "limit": number;
    "where": string;
}

/**
 * BatchPreview 是批量操作的预览结果。
 */
export interface BatchPreview {
    "matched": number;
    "where": string;
    "sample": Item[] | null;
}

/**
 * BatchResult 是批量操作的结果。
 */
export interface BatchResult {
    "matched": number;
    "applied": number;
    "failed": number;
    "firstErr": string;
}

/**
 * BindingView 是「绑定名 → 取值来源路径」。
 */
export interface BindingView {
    "name": string;
    "path": string;
}

/**
 * CaseResultView 是一条算例的结果。
 */
export interface CaseResultView {
    "name": string;
    "passed": boolean;
    "detail": string;
}

/**
 * ClaimRef 是一条被依赖的断言（面向界面）。
 */
export interface ClaimRef {
    "id": string;
    "subject": string;
    "predicate": string;
    "value": string;
    "status": string;
    "confidence": string;
}

/**
 * ConflictGroup 是一组互相冲突的断言。
 */
export interface ConflictGroup {
    "subject": string;
    "predicate": string;
    "claims": Item[] | null;
}

/**
 * ConflictView 是同一场景同一话题的一组不同说法。
 */
export interface ConflictView {
    "scenario": string;
    "topic": string;
    "entries": EntryView[] | null;
}

/**
 * DecisionCandidate 是一个候选取值（面向界面）。
 * 
 * 上下文必填：只给一个数字，人无法判断。
 */
export interface DecisionCandidate {
    "index": number;
    "value": string;
    "unit": string;
    "anchor": string;
    "context": string;
    "note": string;
}

/**
 * DecisionItem 是一个待判定事项（面向界面）。
 */
export interface DecisionItem {
    "id": string;
    "entity": string;
    "subject": string;
    "predicate": string;
    "reason": string;
    "context": string;
    "artifact": string;
    "revision": string;
    "source": string;
    "status": string;
    "statusText": string;

    /**
     * Impact 是被引用次数，ImpactReason 是「为什么排在前面」。
     */
    "impact": number;
    "impactReason": string;
    "candidates": DecisionCandidate[] | null;
    "resolution": DecisionResolution | null;
    "deferredBy": string;
    "deferReason": string;

    /**
     * Editable 报告该事项此刻是否还能裁决。它由状态算出，
     * 免得界面自己判断状态——那会让「能不能点」变成第二套规则。
     */
    "editable": boolean;
}

/**
 * DecisionResolution 是一次裁决（面向界面）。
 */
export interface DecisionResolution {
    "choice": number;

    /**
     * ChosenValue 在「都不对」时为空串。
     */
    "chosenValue": string;
    "by": string;
    "reason": string;
    "method": string;
    "evidence": string;
    "at": string;

    /**
     * AssertionID 在「都不对」时为空串。
     */
    "assertionId": string;
}

/**
 * DecisionResult 是一次裁决的结果。
 */
export interface DecisionResult {
    "applied": boolean;
    "status": string;
    "assertionId": string;
    "message": string;
}

/**
 * DecisionStats 是待判定的整体状态。
 */
export interface DecisionStats {
    "open": number;
    "deferred": number;
    "decided": number;
    "missing": number;
    "stale": number;
}

/**
 * EntityQuality 是一个实体的数据质量。
 */
export interface EntityQuality {
    "entity": string;
    "subjects": number;
    "assertions": number;
    "fields": FieldQuality[] | null;

    /**
     * Undeclared 是数据中出现、schema 未声明的字段。
     */
    "undeclared": string[] | null;

    /**
     * Unused 是 schema 声明、数据中从未出现的字段。
     */
    "unused": string[] | null;

    /**
     * RequiredMissing 是必填但没有任何数据的主体级字段。
     */
    "requiredMissing": string[] | null;
}

/**
 * EntitySchema 是一个实体的声明（面向界面）。
 */
export interface EntitySchema {
    "entity": string;
    "description": string;
    "schemaRev": string;
    "fields": FieldSchema[] | null;
}

/**
 * EntitySummary 是一个实体的规模。
 */
export interface EntitySummary {
    "entity": string;
    "subjects": number;
    "assertions": number;
}

/**
 * EntryView 是一条经验（面向界面）。
 */
export interface EntryView {
    "id": string;
    "scenario": string;
    "topic": string;
    "kind": string;
    "kindText": string;
    "statement": string;
    "rationale": string;
    "chain": string[] | null;
    "sampleSize": number;
    "sampleFrom": string;
    "conditions": string;
    "preference": string;

    /**
     * Level 与 MaxConfidence 都是**算出来的**，界面只显示不提供修改。
     */
    "level": number;
    "levelText": string;
    "maxConfidence": string;
    "proposedBy": ActorView;
    "collaborators": ActorView[] | null;

    /**
     * ApprovedBy 为 null 表示尚未批准。
     */
    "approvedBy": ActorView | null;
    "approveReason": string;
    "sessionId": string;
    "anchor": string;
    "status": string;
    "statusText": string;
    "usable": boolean;
    "at": string;
    "supersedes": string;
    "conflictsWith": string[] | null;
}

/**
 * EvaluationView 是一次对比呈现。
 */
export interface EvaluationView {
    /**
     * Plans 是剪枝与合并之后留下的方案。**已选中的排在最前，其余仍在。**
     */
    "plans": PlanView[] | null;
    "pruned": PrunedView[] | null;

    /**
     * Merged 是被合并的组（每组第一个是保留者）。
     */
    "merged": (string[] | null)[] | null;

    /**
     * Constraints 在没有任何方案可呈现时给出冲突的约束清单。
     */
    "constraints": string[] | null;

    /**
     * Note 是人话说明：只有一个方案时要说清「未发现实质不同的备选」。
     */
    "note": string;

    /**
     * PreferenceInferred 是一个**建议**，必须经人确认才生效。
     */
    "preferenceInferred": string;
}

/**
 * ExternalInput 是本次使用的一个外部输入。**始终标注未核验**。
 */
export interface ExternalInput {
    "name": string;
    "value": string;
    "why": string;
}

/**
 * FieldQuality 是一个字段的数据质量。
 */
export interface FieldQuality {
    "key": string;

    /**
     * Declared 报告该字段是否在 schema 中声明。
     * 
     * 未声明的字段出现在数据里就是**漂移**：它会被准入层过滤掉，
     * 于是数据「看起来接进来了」但根本没入库。
     */
    "declared": boolean;
    "required": boolean;

    /**
     * Coverage 是覆盖的主体数占比（0..1）；未声明字段为 0。
     */
    "coverage": number;

    /**
     * Subjects 是出现该字段的主体数。
     */
    "subjects": number;
}

/**
 * FieldSchema 是一个字段的声明（面向界面）。
 */
export interface FieldSchema {
    "key": string;
    "description": string;
    "type": string;
    "unit": string;
    "required": boolean;
    "identity": boolean;
    "unique": boolean;
    "target": string;
    "values": string[] | null;
    "min": number | null;
    "max": number | null;
}

/**
 * FilterInput 是批量筛选条件（面向界面）。
 */
export interface FilterInput {
    "entity": string;
    "status": string;
    "predicate": string;
    "artifact": string;
    "revision": string;
    "confidence": string;
    "subject": string;
    "limit": number;
}

/**
 * FormulaCaseView 是一条算例的结果。
 */
export interface FormulaCaseView {
    "name": string;
    "passed": boolean;
    "got": string;
    "want": string;
    "detail": string;
}

/**
 * FormulaParamView 是一个公式参数的静态声明。
 */
export interface FormulaParamView {
    "name": string;
    "type": string;
    "unit": string;
    "note": string;
}

/**
 * FormulaStatusView 是一个依赖公式的状态（面向界面）。
 */
export interface FormulaStatusView {
    "name": string;
    "status": string;

    /**
     * Cases 是算例的通过情况。
     */
    "cases": CaseResultView[] | null;
}

/**
 * FormulaView 是一条公式（面向界面）。
 */
export interface FormulaView {
    "name": string;
    "version": string;
    "description": string;

    /**
     * Result 是结果表达式的**原文**。界面把它显示出来，
     * 因为一个不透明的公式没法被审阅——而算错的公式比算错的数据更难发现。
     */
    "result": string;
    "params": FormulaParamView[] | null;
    "bindings": BindingView[] | null;

    /**
     * Status 是 verified / unverified / failed / unreadable。
     */
    "status": string;
    "cases": FormulaCaseView[] | null;

    /**
     * Error 仅在公式读不出来时非空。
     */
    "error": string;

    /**
     * File 是它来自哪个文件，便于去改。
     */
    "file": string;

    /**
     * UsedBy 是哪些场景在用它。
     */
    "usedBy": string[] | null;
}

/**
 * Glossary 是本项目的词表。
 */
export interface Glossary {
    /**
     * Entities 是实体类型：shikigami -> 式神。
     */
    "entities": { [_ in string]?: Term } | null;

    /**
     * Fields 是字段：`shikigami.atk` -> 攻击。
     */
    "fields": { [_ in string]?: Term } | null;

    /**
     * Units 是单位：percent -> 百分比。
     */
    "units": { [_ in string]?: Term } | null;

    /**
     * Types 是字段类型：number -> 数值。
     */
    "types": { [_ in string]?: Term } | null;

    /**
     * Subjects 是主体的显示名：`shikigami/262` -> 姑获鸟。
     * 
     * 它是**从数据里读出来的**，不是编的：主体标识是稳定身份，
     * 而名字就在同一条记录上。
     */
    "subjects": { [_ in string]?: string } | null;
    "confidences": { [_ in string]?: Term } | null;
    "statuses": { [_ in string]?: Term } | null;
    "actorKinds": { [_ in string]?: Term } | null;
    "expKinds": { [_ in string]?: Term } | null;
    "expStatuses": { [_ in string]?: Term } | null;
    "decStatuses": { [_ in string]?: Term } | null;
    "planStatuses": { [_ in string]?: Term } | null;
    "methods": { [_ in string]?: Term } | null;
}

/**
 * HistoryItem 是一条核验记录（面向界面）。
 */
export interface HistoryItem {
    "decision": string;
    "method": string;
    "proposedBy": string;
    "approvedBy": string;
    "reason": string;
    "evidence": string;
    "at": string;
}

/**
 * InputSpecView 是一个外部输入的声明（面向界面）。
 * 
 * Unit 与 Min/Max 必须暴露给界面：没有量纲的输入框就是一个歧义制造机，
 * 而声明了范围却不校验比不声明更糟——那会让人以为自己被保护着。
 */
export interface InputSpecView {
    "name": string;
    "description": string;
    "unit": string;
    "min": number | null;
    "max": number | null;
}

/**
 * Item 是队列里的一条断言（面向界面的扁平结构）。
 */
export interface Item {
    "id": string;
    "entity": string;
    "subject": string;
    "predicate": string;
    "value": string;
    "unit": string;
    "confidence": string;
    "status": string;
    "source": string;
    "artifact": string;
    "anchor": string;
    "revision": string;
}

/**
 * MetricView 是一个可比的维度。
 */
export interface MetricView {
    "name": string;
    "value": number;
    "unit": string;
    "lowerIsBetter": boolean;
}

/**
 * OutputValue 是一项参与计算的输入。
 */
export interface OutputValue {
    "name": string;
    "value": string;
    "unit": string;
}

/**
 * PlanProposalInput 是一次提出。
 */
export interface PlanProposalInput {
    "scenario": string;
    "title": string;
    "objective": string;
    "constraints": string[] | null;
    "assumptions": string[] | null;
    "preference": string;
    "actions": string[] | null;
    "metrics": MetricView[] | null;
    "opportunity": string;
    "depends": string[] | null;
    "sources": string[] | null;
    "fromConflict": boolean;
}

/**
 * PlanRefreshView 是一次依据检查的结果。
 */
export interface PlanRefreshView {
    "checked": number;
    "invalid": string[] | null;
    "stale": string[] | null;
}

/**
 * PlanView 是一个方案（面向界面）。
 */
export interface PlanView {
    "id": string;
    "scenario": string;
    "title": string;

    /**
     * Objective 是它优化的东西。**必填**——不声明目标的方案无法被比较。
     */
    "objective": string;
    "constraints": string[] | null;
    "assumptions": string[] | null;

    /**
     * Preference 是它假设的偏好。未声明偏好时每个备选都必须标注。
     */
    "preference": string;
    "actions": string[] | null;
    "metrics": MetricView[] | null;

    /**
     * Opportunity 是机会成本。**必填**——最容易在事后才发现的一项。
     */
    "opportunity": string;
    "depends": string[] | null;
    "unverifiedRatio": number;

    /**
     * MaxConfidence 不得高于依赖断言中的最低。
     */
    "maxConfidence": string;
    "sources": string[] | null;
    "fromConflict": boolean;
    "status": string;
    "statusText": string;

    /**
     * Executable 报告该方案能否被执行。
     */
    "executable": boolean;

    /**
     * Chosen 报告它是不是被选中的那个。**其他备选仍然可访问。**
     */
    "chosen": boolean;
    "chosenBy": string;
    "chooseReason": string;
    "at": string;
}

/**
 * ProjectOverview 是项目概览（面向界面）。
 */
export interface ProjectOverview {
    "dir": string;
    "name": string;
    "path": string;
    "description": string;
    "entities": EntitySummary[] | null;
    "assertions": number;
    "byStatus": { [_ in string]?: number } | null;
    "byConfidence": { [_ in string]?: number } | null;
    "verifications": number;
    "conflicts": number;
    "decisions": number;
    "scenarioCount": number;
    "formulaCount": number;

    /**
     * EntityTypes 是 schema 中声明的实体类型数（含尚无数据的）。
     */
    "entityTypes": number;
}

/**
 * ProjectRef 是一个可选的项目（面向界面）。
 */
export interface ProjectRef {
    "dir": string;
    "name": string;

    /**
     * Path 是完整路径。两个项目目录同名是允许的，
     * 因此界面上必须显示完整路径才能区分。
     */
    "path": string;
    "description": string;

    /**
     * Current 标记它是不是当前打开的那个。
     */
    "current": boolean;
}

/**
 * ProposalInput 是一次提出。
 */
export interface ProposalInput {
    "scenario": string;
    "topic": string;
    "kind": string;
    "statement": string;
    "rationale": string;
    "chain": string[] | null;
    "sampleSize": number;
    "sampleFrom": string;
    "conditions": string;
    "preference": string;
    "sessionId": string;
    "anchor": string;
    "proposedByKind": string;
    "proposedById": string;

    /**
     * Collaborators 里出现人即判为「协作」。
     */
    "collaborators": ActorView[] | null;
}

/**
 * PrunedView 记录一个被剪掉的方案及原因。
 */
export interface PrunedView {
    "plan": PlanView;

    /**
     * By 是支配它的那个方案的 ID。
     */
    "by": string;
    "dominance": string;
}

/**
 * QueueItem 是带优先级的队列项。
 * 
 * 除了断言本身，它还带上「为什么排在前面」——排在前面的理由必须可见，
 * 否则人只能盲信排序。
 */
export interface QueueItem {
    "item": Item;
    "tier": string;
    "reason": string;
    "score": number;
    "sampled": boolean;
}

/**
 * RefCandidates 是一个「取自其他实体」的绑定及其候选。
 */
export interface RefCandidates {
    "name": string;
    "entity": string;
    "via": string;
    "description": string;

    /**
     * Candidates 是该主实体下可选的来源主体；未选主实体时为空。
     */
    "candidates": string[] | null;
}

/**
 * RefInput 是一个「取自其他实体」的绑定。
 */
export interface RefInput {
    "name": string;
    "subject": string;
}

/**
 * RefreshResultView 是一次依赖检查的结果。
 */
export interface RefreshResultView {
    "checked": number;
    "staled": string[] | null;
    "recompute": string[] | null;
}

/**
 * RequirementView 是一项 requires 的检查结果（面向界面）。
 */
export interface RequirementView {
    "want": string;
    "status": string;
    "have": number;
    "total": number;
    "coverage": number;
    "detail": string;
}

/**
 * RunInput 是一个外部输入。
 */
export interface RunInput {
    "name": string;
    "value": string;

    /**
     * Unit 为空时按声明补全；声明也没有则拒绝。
     */
    "unit": string;
}

/**
 * RunResult 是一次运行的结果。
 */
export interface RunResult {
    "ok": boolean;
    "scenario": string;
    "subject": string;
    "result": string;
    "resultUnit": string;

    /**
     * Bindings 是参与计算的每一项取值，含它来自哪里。
     */
    "bindings": OutputValue[] | null;
    "notes": string[] | null;

    /**
     * UnverifiedRatio 是本次产出所依赖的**未核验比例**（0..1）。
     */
    "unverifiedRatio": number;
    "unverified": ClaimRef[] | null;
    "external": ExternalInput[] | null;
    "requires": RequirementView[] | null;
    "missing": string[] | null;

    /**
     * Message 是人话结果或拒绝原因。
     */
    "message": string;

    /**
     * At 是运行时刻，便于把界面上看到的数字与某一次运行对上。
     */
    "at": string;
}

/**
 * RunSetup 是运行一个场景所需的全部输入（面向界面）。
 */
export interface RunSetup {
    "scenario": string;

    /**
     * Entity 是主实体，主体从这里选。
     */
    "entity": string;

    /**
     * Subjects 是主实体上的可选主体。
     */
    "subjects": string[] | null;

    /**
     * Subject 是当前选中的主体；null 表示未选。
     */
    "subject": string | null;

    /**
     * Runnable 报告 requires 是否满足。不满足时界面必须挡住运行按钮。
     */
    "runnable": boolean;
    "requires": RequirementView[] | null;
    "missing": string[] | null;
    "inputs": InputSpecView[] | null;
    "refs": RefCandidates[] | null;
}

/**
 * ScenarioOverview 是场景概览（面向界面）。
 */
export interface ScenarioOverview {
    "name": string;
    "description": string;

    /**
     * Runnable 报告 requires 是否全部满足。
     */
    "runnable": boolean;

    /**
     * Requires 逐项列出「需要什么 / 现有多少 / 覆盖率」——
     * 只报一个总数等于没报。
     */
    "requires": RequirementView[] | null;
    "inputs": InputSpecView[] | null;
    "formulas": FormulaStatusView[] | null;
    "outputs": string[] | null;

    /**
     * Missing 是缺失项的人话清单，供界面直接显示。
     */
    "missing": string[] | null;
}

/**
 * ScenarioRef 是一个可选的场景（面向界面）。
 */
export interface ScenarioRef {
    "name": string;
    "description": string;

    /**
     * Inputs 是需要外部输入的项数。
     */
    "inputs": number;

    /**
     * RequiresMet 报告 requires 是否全部满足。
     */
    "requiresMet": boolean;

    /**
     * RequiresTotal 是 requires 的项数，用于显示「3 项中 2 项满足」。
     */
    "requiresTotal": number;

    /**
     * Skipped 说明该场景为什么不可用；空串表示可用。
     */
    "skipped": string;
}

/**
 * SessionState 是当前会话（面向界面）。
 */
export interface SessionState {
    "dir": string;
    "name": string;
    "projectDir": string;

    /**
     * Description 是 project.yml 里的描述。
     */
    "description": string;

    /**
     * Scenarios 是该项目的场景，按名称排序。
     */
    "scenarios": ScenarioRef[] | null;

    /**
     * Scenario 是当前场景名；null 表示未选中或该项目没有场景。
     */
    "scenario": string | null;

    /**
     * ScenarioSkipped 是被跳过的场景目录及原因。**必须显示**：
     * 一场静默的跳过会让人以为「项目只有两个场景」。
     */
    "scenarioSkipped": SkippedRef[] | null;
}

/**
 * SessionView 是一段会话记录（依据）。
 */
export interface SessionView {
    "id": string;
    "scenario": string;
    "title": string;
    "at": string;
    "turns": TurnView[] | null;
}

/**
 * SkippedRef 是一个被跳过的场景目录。
 */
export interface SkippedRef {
    "dir": string;
    "reason": string;
}

/**
 * Stats 是库的整体状态。
 */
export interface Stats {
    "total": number;
    "byStatus": { [_ in string]?: number } | null;
    "byEntity": { [_ in string]?: number } | null;
    "byConfidence": { [_ in string]?: number } | null;
    "verifications": number;
    "conflicts": number;
}

/**
 * Term 是一个词条：给人看的名字 + 完整说明。
 */
export interface Term {
    /**
     * Key 是原始标识符。**必须一起显示**——中文名给人看，标识符给对账用。
     */
    "key": string;

    /**
     * Label 是短名。空串表示定义里没有中文，界面应退回显示 Key。
     */
    "label": string;

    /**
     * Note 是完整说明。
     */
    "note": string;

    /**
     * Extra 是附加信息（单位、类型、目标实体等），可为空。
     */
    "extra": string;
}

/**
 * TurnView 是会话中的一段发言。
 */
export interface TurnView {
    "seq": number;
    "role": ActorView;
    "text": string;
    "at": string;
}
