// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService 暴露项目与会话。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Current 返回当前会话。
 */
export function Current(): $CancellablePromise<$models.SessionState> {
    return $Call.ByID(1610103818);
}

/**
 * Glossary 返回本项目的词表。
 */
export function Glossary(): $CancellablePromise<$models.Glossary> {
    return $Call.ByID(2971284389);
}

/**
 * Open 切换项目。**失败时会话不变**，因此界面不会塌成空白。
 */
export function Open(dir: string): $CancellablePromise<$models.SessionState> {
    return $Call.ByID(522968697, dir);
}

/**
 * Overview 返回项目概览：规模、状态与分级分布、缺口。
 */
export function Overview(): $CancellablePromise<$models.ProjectOverview> {
    return $Call.ByID(2882841514);
}

/**
 * Projects 列出项目根目录下的全部项目，按目录名排序。
 */
export function Projects(): $CancellablePromise<$models.ProjectRef[] | null> {
    return $Call.ByID(4043538951);
}
