// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReviewService 是核验工作台的后端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Approve 批准一条断言。
 * 
 * by 必须是人——agent 可以提出与取证，但不能自己决定什么算数。
 * 这条规则在领域层的 Validate 中强制，此处只做转发。
 */
export function Approve(id: string, by: string, method: string, reason: string, evidence: string): $CancellablePromise<void> {
    return $Call.ByID(3028409479, id, by, method, reason, evidence);
}

/**
 * BatchApprove 批量批准。每条断言各自留下核验记录，审计轨迹不合并。
 */
export function BatchApprove(f: $models.FilterInput, by: string, method: string, reason: string, evidence: string): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(2878733075, f, by, method, reason, evidence).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BatchPreview 展示批量操作会选中什么——**执行前必须能看见影响面**。
 */
export function BatchPreview(f: $models.FilterInput): $CancellablePromise<$models.BatchPreview> {
    return $Call.ByID(4077936422, f).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BatchReject 批量驳回。
 */
export function BatchReject(f: $models.FilterInput, by: string, reason: string): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(473055153, f, by, reason).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Conflicts 返回冲突分组。**系统不裁决**，只把同一件事的说法摆在一起。
 */
export function Conflicts(): $CancellablePromise<$models.ConflictGroup[]> {
    return $Call.ByID(641064245).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * History 返回某断言的核验历史。
 */
export function History(id: string): $CancellablePromise<$models.HistoryItem[]> {
    return $Call.ByID(3004648246, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Pending 返回待核验队列（不排序，按主体谓词）。
 */
export function Pending(entity: string, status: string, limit: number): $CancellablePromise<$models.Item[]> {
    return $Call.ByID(1871646081, entity, status, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ProjectDir 返回项目目录，供界面显示。
 */
export function ProjectDir(): $CancellablePromise<string> {
    return $Call.ByID(50586622);
}

/**
 * Queue 返回**按优先级排序**的核验队列，并强制包含抽检项。
 */
export function Queue(entity: string, status: string, limit: number, sampleRatio: number): $CancellablePromise<$models.QueueItem[]> {
    return $Call.ByID(3654268873, entity, status, limit, sampleRatio).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Reject 驳回一条断言。
 */
export function Reject(id: string, by: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(888414013, id, by, reason);
}

/**
 * Stats 返回库的整体状态。
 */
export function Stats(): $CancellablePromise<$models.Stats> {
    return $Call.ByID(268982341).then(($result: any) => {
        return $$createType10($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BatchResult.createFrom;
const $$createType1 = $models.BatchPreview.createFrom;
const $$createType2 = $models.ConflictGroup.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.HistoryItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Item.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.QueueItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.Stats.createFrom;
