// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReviewService 是核验工作台的后端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Approve 批准一条断言。
 * 
 * by 必须是人——agent 可以提出与取证，但不能自己决定什么算数。
 * 这条规则在领域层的 Validate 中强制，此处只做转发。
 */
export function Approve(id: string, by: string, method: string, reason: string, evidence: string): $CancellablePromise<void> {
    return $Call.ByID(3028409479, id, by, method, reason, evidence);
}

/**
 * History 返回某断言的核验历史。
 */
export function History(id: string): $CancellablePromise<$models.HistoryItem[]> {
    return $Call.ByID(3004648246, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Pending 返回待核验队列。
 */
export function Pending(entity: string, status: string, limit: number): $CancellablePromise<$models.Item[]> {
    return $Call.ByID(1871646081, entity, status, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ProjectDir 返回项目目录，供界面显示。
 */
export function ProjectDir(): $CancellablePromise<string> {
    return $Call.ByID(50586622);
}

/**
 * Reject 驳回一条断言。
 */
export function Reject(id: string, by: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(888414013, id, by, reason);
}

/**
 * Stats 返回库的整体状态。
 */
export function Stats(): $CancellablePromise<$models.Stats> {
    return $Call.ByID(268982341).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.HistoryItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Item.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Stats.createFrom;
