// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScenarioService 暴露场景。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List 返回当前项目的场景，按名称排序。
 */
export function List(): $CancellablePromise<$models.ScenarioRef[] | null> {
    return $Call.ByID(1332543624);
}

/**
 * Overview 返回场景概览：requires 逐项、外部输入声明、依赖公式与输出。
 */
export function Overview(name: string): $CancellablePromise<$models.ScenarioOverview> {
    return $Call.ByID(1390931939, name);
}

/**
 * Select 选中一个场景。名称必须在该项目的场景列表中。
 */
export function Select(name: string): $CancellablePromise<$models.SessionState> {
    return $Call.ByID(3087910632, name);
}
